export const HOME_URL = "/"
export const DEVICES_URL = "/devices"
export const FILES_URL = "/files"
export const REGISTER_URL = "/register"
export const PASSWORD_RECOVERY_URL = "/password-recovery"
export const CHANGE_PASSWORD_URL = "/change-password"
