export const HOME_URL = "/"
export const FILES_URL = "/files"
export const DEVICE_URL = "/device/"
export const REGISTER_URL = "/register"
export const ADD_DEVICE_URL = "/add-devices"
export const UPDATE_DEVICE_URL = "/update-devices/"
export const CHANGE_PASSWORD_URL = "/change-password"
export const PASSWORD_RECOVERY_URL = "/password-recovery"